const page = () => {
    return (
        <main className='section h-screen padding-x pt-36 pb-12 flex justify-center items-center'>
            <p className="inline-block"><strong>DISCLAIMER</strong>: ALL INFORMATION INCLUDED ON THIS WEBSITE IS FOR GENERAL INFORMATION PURPOSES ONLY AND NOT INTENDED AS LEGAL ADVICE. THIS SITE CONSTITUTES ATTORNEY ADVERTISING. ANY INFORMATION IS NOT INTENDED TO CREATE, AND RECEIPT OR VIEWING DOES NOT CONSTITUTE, AN ATTORNEY-CLIENT RELATIONSHIP. UNTIL HENDLEY & GOODWYN, LLP IS RETAINED AS EVIDENCED BY AN EXECUTED LEGAL REPRESENTATION AGREEMENT AND A RETAINER IS PAID IN FULL, AN ATTORNEY-CLIENT RELATIONSHIP DOES NOT EXIST. AS SUCH, HENDLEY & GOODWYN, LLP SHALL NOT BE DEEMED TO HAVE GIVEN YOU ANY ADVICE AND ANY INFORMATION YOU MAY PROVIDE HENDLEY & GOODWYN, LLP SHALL NOT BE DEEMED PRIVILEGED AND CONFIDENTIAL.</p>
        </main>
    )
}

export default page;   